import type { NextPage, InferGetServerSidePropsType } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import classes from '../styles/Home.module.css'
import { fetchCountries, normalizeCountriesData, Country } from '../utils'

import { AiOutlineSearch as SearchIcon } from 'react-icons/ai'
import CountryCard from '../components/countryCard'

const Home = ({ 
  countries,
 }: InferGetServerSidePropsType<typeof getServerSideProps>) => {

  const first40Countries = countries.slice(0, 40);

  return (
    <div className={classes.home}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={["container", classes.container].join(" ")}>
        <div className={`pb-6 flex justify-between ${classes.top}`}>

          <div className={`p-2 flex items-center bg-primary dark:bg-primary-dark shadow-sm rounded-sm px-4 ${classes.searchContainer}`}>
            <SearchIcon className='' />
            <input type="text" className={`bg-transparent text-sm w-full ${classes.input}`} placeholder="Search for a country" />
          </div>

          <div className={`p-2 ${classes.filterContainer}`}></div>

        </div>

        <div className={`main ${classes.main}`}>
          <div className={`countries flex flex-wrap justify-between ${classes.countries}`}>
            {first40Countries.map((country: Country, index) => (
              <CountryCard key={index} country={country} />
            ))}
          </div>
          
        </div>
      </div>
    </div>
  )
}

export const getServerSideProps = async () => {
  const data = await fetchCountries();
  const countries = normalizeCountriesData(data);

  return {
    props: {
      countries: JSON.parse(JSON.stringify(countries)) as Country[],
    },
  }
}

export default Home
